title: MTH Pinnacle
description: Wholesale & Distribution

url: "https://chew-max.github.io"
baseurl: "/mth-pinnacle"

remote_theme: dieghernan/chulapa

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

chulapa-skin:
  vars:
    primary: "#0D5FB8"
    secondary: "#C6A15B"
    dark: "#06264D"
    light: "#F6F8FB"