title: MTH Pinnacle
description: Wholesale & Distribution

url: "https://chew-max.github.io"
baseurl: "/mth-pinnacle"

remote_theme: dieghernan/chulapa

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

chulapa-skin:
  vars:
    primary: "#0D5FB8"
    secondary: "#C6A15B"
    dark: "#06264D"
    light: "#F6F8FB"
    
    
navbar:
  style: fab

  brand:
    title: MTH Pinnacle
    url: /mth-pinnacle/

  nav:
    - title: Home
      url: /mth-pinnacle/

    - title: Contact
      url: /mth-pinnacle/contact.html
      
footer:
  copyright: "© 2026 MTH Pinnacle LLC. All Rights Reserved."